version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch
    restart: unless-stopped

  web_server:
    image: web_server:latest
    container_name: web_server
    ports:
      - 80:80
    restart: unless-stopped

  data_receiver:
    image: data_receiver:latest
    container_name: data_receiver
    ports:
      - 8080:8080
    restart: unless-stopped


volumes:
  esdata:
    driver: local
